import { StyleSheet } from 'react-native'
import { sBarHeight } from '/home/Jorge/github/fork/appv1/constants/Layout'

export default StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    }, 
    subContainer: {
      flex: 0.32,
      alignItems: 'center',
      justifyContent: 'space-evenly',
      paddingHorizontal: 12,
    },
    oneContainer: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
    },
    oneItemContainer: {
      flexDirection: 'row',
      flex: 1,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: '#0041c4ff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      elevation: 2,
    },
    oneTitleContainer: {
      justifyContent: 'center',
      paddingLeft: 20,
      flex:1,
    },
    oneTitle: { 
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    oneCounterContainer: {
      flex: 1,
      height:'80%',
      paddingRight: 6,
  
    },
    oneCounterSubContainer: {
      flex: 1,
      height:'100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 2,
    },
    oneCounter: {
      color: '#0041c4ff',
      fontSize: 20,
    },
    twoContainer: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
    },
    twoItemContainer: {
      flexDirection: 'row',
      flex: 1,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: '#0041c4ff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      elevation: 2,
    },
    twoTitleContainer: {
      justifyContent: 'center',
      paddingLeft: 20,
      flex:1,
    },
    twoTitle: { 
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    twoCounterContainer: {
      flex: 1,
      height:'80%',
      paddingRight: 6,
  
    },
    twoCounterSubContainer: {
      flex: 1,
      height:'100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 2,
    },
    twoCounter: {
      color: '#0041c4ff',
      fontSize: 20,
    },
    threeContainer: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 12,
    },
    threeItemContainer: {
      flexDirection: 'row',
      flex: 1,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: '#0041c4ff',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 2,
      elevation: 2,
    },
    threeTitleContainer: {
      justifyContent: 'center',
      paddingLeft: 20,
      flex:1,
    },
    threeTitle: { 
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
    threeCounterContainer: {
      flex: 1,
      height:'80%',
      paddingRight: 6,
  
    },
    threeCounterSubContainer: {
      flex: 1,
      height:'100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderRadius: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.5,
      shadowRadius: 12,
      elevation: 2,
    },
    threeCounter: {
      color: '#0041c4ff',
      fontSize: 20,
    },
  })